"""
Descriptor dictionary for BoFire CategoricalDescriptorInput
Auto-generated from RDKit calculations + experimental data
"""

BASE_DESCRIPTORS = {
    "Cesium carbonate": {
        "AromaticRings": 0,
        "CAS": "534-17-8",
        "FractionCSP3": 0.0,
        "HBA": 3,
        "HBD": 0,
        "HeavyAtoms": 6,
        "LogP": -8.44,
        "MW": 325.82,
        "MolMR": 5.4,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 5,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 63.19,
        "basicity": 10.3,
        "nucleophilicity": "Very low",
        "pKa": 10.3,
    },
    "DBN": {
        "AromaticRings": 0,
        "CAS": "3001-72-7",
        "FractionCSP3": 0.875,
        "HBA": 2,
        "HBD": 0,
        "HeavyAtoms": 10,
        "LogP": 1.27,
        "MW": 138.21,
        "MolMR": 42.34,
        "NumAliphaticRings": 2,
        "NumHeteroatoms": 2,
        "NumRings": 2,
        "NumSaturatedRings": 1,
        "RotBonds": 0,
        "TPSA": 15.6,
        "basicity": 14.0,
        "nucleophilicity": "Low",
        "pKa": 14.0,
    },
    "DBU": {
        "AromaticRings": 0,
        "CAS": "6674-22-2",
        "FractionCSP3": 0.875,
        "HBA": 2,
        "HBD": 0,
        "HeavyAtoms": 10,
        "LogP": 1.27,
        "MW": 138.21,
        "MolMR": 42.34,
        "NumAliphaticRings": 2,
        "NumHeteroatoms": 2,
        "NumRings": 2,
        "NumSaturatedRings": 1,
        "RotBonds": 0,
        "TPSA": 15.6,
        "basicity": 13.5,
        "nucleophilicity": "Low",
        "pKa": 13.5,
    },
    "DIPEA": {
        "AromaticRings": 0,
        "CAS": "7087-68-5",
        "FractionCSP3": 1.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 9,
        "LogP": 2.13,
        "MW": 129.25,
        "MolMR": 42.65,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 1,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 3,
        "TPSA": 3.24,
        "basicity": 11.0,
        "nucleophilicity": "Low",
        "pKa": 11.0,
    },
        "LDA": {
        "AromaticRings": 0,
        "CAS": "4111-54-0",
        "FractionCSP3": 1.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 8,
        "LogP": 2.8,
        "MW": 107.11,
        "MolMR": 35.5,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 2,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 4,
        "TPSA": 3.24,
        "basicity": 18.0,
        "nucleophilicity": "High",
        "pKa": 35.7,
    },
    "MTBD": {
        "AromaticRings": 0,
        "CAS": "84030-20-6",
        "FractionCSP3": 0.857,
        "HBA": 3,
        "HBD": 0,
        "HeavyAtoms": 10,
        "LogP": -0.35,
        "MW": 139.2,
        "MolMR": 41.37,
        "NumAliphaticRings": 2,
        "NumHeteroatoms": 3,
        "NumRings": 2,
        "NumSaturatedRings": 1,
        "RotBonds": 0,
        "TPSA": 18.84,
        "basicity": 25.0,
        "nucleophilicity": "Very low",
        "pKa": 25.0,
    },
    "Potassium carbonate": {
        "AromaticRings": 0,
        "CAS": "584-08-7",
        "FractionCSP3": 0.0,
        "HBA": 3,
        "HBD": 0,
        "HeavyAtoms": 6,
        "LogP": -8.44,
        "MW": 138.2,
        "MolMR": 5.4,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 5,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 63.19,
        "basicity": 10.3,
        "nucleophilicity": "Very low",
        "pKa": 10.3,
    },
    "Potassium hydroxide": {
        "AromaticRings": 0,
        "CAS": "1310-58-3",
        "FractionCSP3": 0.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 2,
        "LogP": -3.17,
        "MW": 56.11,
        "MolMR": 1.94,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 2,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 30.0,
        "basicity": 15.7,
        "nucleophilicity": "High",
        "pKa": 15.7,
    },
    "Potassium tert-butoxide": {
        "AromaticRings": 0,
        "CAS": "865-47-4",
        "FractionCSP3": 1.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 6,
        "LogP": -2.85,
        "MW": 112.21,
        "MolMR": 19.75,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 2,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 23.06,
        "basicity": 19.0,
        "nucleophilicity": "Moderate",
        "pKa": 19.0,
    },
    "Pyridine": {
        "AromaticRings": 1,
        "CAS": "110-86-1",
        "FractionCSP3": 0.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 6,
        "LogP": 1.08,
        "MW": 79.1,
        "MolMR": 24.24,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 1,
        "NumRings": 1,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 12.89,
        "basicity": 5.25,
        "nucleophilicity": "Moderate",
        "pKa": 5.25,
    },
    "Sodium bicarbonate": {
        "AromaticRings": 0,
        "CAS": "144-55-8",
        "FractionCSP3": 0.0,
        "HBA": 2,
        "HBD": 1,
        "HeavyAtoms": 5,
        "LogP": -4.11,
        "MW": 84.01,
        "MolMR": 8.02,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 4,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 60.36,
        "basicity": 6.3,
        "nucleophilicity": "Very low",
        "pKa": 6.3,
    },
    "Sodium hydroxide": {
        "AromaticRings": 0,
        "CAS": "1310-73-2",
        "FractionCSP3": 0.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 2,
        "LogP": -3.17,
        "MW": 40.0,
        "MolMR": 1.94,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 2,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 30.0,
        "basicity": 14.0,
        "nucleophilicity": "High",
        "pKa": 14.0,
    },
    "TBD": {
        "AromaticRings": 0,
        "CAS": "5807-14-7",
        "FractionCSP3": 0.8,
        "HBA": 4,
        "HBD": 2,
        "HeavyAtoms": 9,
        "LogP": -1.23,
        "MW": 126.16,
        "MolMR": 35.01,
        "NumAliphaticRings": 2,
        "NumHeteroatoms": 4,
        "NumRings": 2,
        "NumSaturatedRings": 1,
        "RotBonds": 0,
        "TPSA": 39.66,
        "basicity": 26.0,
        "nucleophilicity": "Very low",
        "pKa": 26.0,
    },
    "TMG": {
        "AromaticRings": 0,
        "CAS": "80-70-6",
        "FractionCSP3": 0.8,
        "HBA": 1,
        "HBD": 1,
        "HeavyAtoms": 8,
        "LogP": 0.04,
        "MW": 115.18,
        "MolMR": 35.1,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 3,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 0,
        "TPSA": 30.33,
        "basicity": 23.0,
        "nucleophilicity": "Low",
        "pKa": 23.0,
    },
    "Triethylamine": {
        "AromaticRings": 0,
        "CAS": "121-44-8",
        "FractionCSP3": 1.0,
        "HBA": 1,
        "HBD": 0,
        "HeavyAtoms": 7,
        "LogP": 1.35,
        "MW": 101.19,
        "MolMR": 33.46,
        "NumAliphaticRings": 0,
        "NumHeteroatoms": 1,
        "NumRings": 0,
        "NumSaturatedRings": 0,
        "RotBonds": 3,
        "TPSA": 3.24,
        "basicity": 10.75,
        "nucleophilicity": "Moderate",
        "pKa": 10.75,
    },
}