"""
Online Analysis Panel Component
Provides UI for connecting REACTO to an online analysis tool.

Features:
- File path configuration
- Auto-detection of keys in the result file
- Dynamic mapping of file keys → domain objectives
- Real-time monitoring with activity log
- Works with any number of objectives
"""

import dash_bootstrap_components as dbc
from dash import dcc, html


def create_online_analysis_panel():
    """
    Create the Online Analysis panel for the Opt-run page.
    
    Returns:
        dbc.Card: The complete online analysis UI component
    """
    return dbc.Card([
        dbc.CardHeader([
            dbc.Row([
                dbc.Col([
                    html.Div([
                        html.I(className="bi bi-broadcast me-2", 
                              style={"fontSize": "1.1rem", "color": "#6366f1"}),
                        html.H5("Online Analysis", className="mb-0 d-inline", 
                                style={"fontWeight": "600"})
                    ])
                ]),
                dbc.Col([
                    dbc.Switch(
                        id="online-analysis-toggle",
                        value=False,
                        className="float-end",
                        style={"fontSize": "1.2rem"}
                    )
                ], width="auto")
            ], align="center")
        ], style={"backgroundColor": "#f8f9fa", "padding": "0.75rem 1rem"}),
        
        dbc.CardBody([
            # ===== CONFIGURATION SECTION (visible when OFF) =====
            html.Div(id="online-analysis-config", children=[
                # File path input
                dbc.Row([
                    dbc.Col([
                        dbc.Label("Result file path", className="fw-bold mb-1",
                                 style={"fontSize": "0.85rem"}),
                        dbc.InputGroup([
                            dbc.InputGroupText(
                                html.I(className="bi bi-file-earmark-text"),
                                style={"backgroundColor": "#f0f0f0"}
                            ),
                            dbc.Input(
                                id="online-analysis-filepath",
                                type="text",
                                placeholder="/path/to/results.txt",
                                persistence=True,
                                persistence_type="session",
                                style={"fontSize": "0.85rem"}
                            ),
                        ], size="sm"),
                        html.Small(
                            "Path to the text file generated by the online analysis tool "
                            "(format: key = value, blocks separated by blank lines)",
                            className="text-muted",
                            style={"fontSize": "0.75rem"}
                        )
                    ], md=8, className="mb-3"),
                    
                    # Polling interval
                    dbc.Col([
                        dbc.Label("Poll interval (s)", className="fw-bold mb-1",
                                 style={"fontSize": "0.85rem"}),
                        dbc.Input(
                            id="online-analysis-interval",
                            type="number",
                            value=5,
                            min=2,
                            max=60,
                            step=1,
                            size="sm",
                            style={"fontSize": "0.85rem"}
                        ),
                    ], md=4, className="mb-3"),
                ]),
                
                # Validate button
                dbc.Row([
                    dbc.Col([
                        dbc.Button([
                            html.I(className="bi bi-search me-2"),
                            "Detect File Keys"
                        ],
                        id="online-analysis-validate-btn",
                        color="secondary",
                        outline=True,
                        size="sm",
                        style={"fontWeight": "500"}
                        ),
                    ], className="mb-3")
                ]),
                
                # Validation message
                html.Div(id="online-analysis-validation-msg", className="mb-3"),
                
                # Key mapping section (populated dynamically after validation)
                html.Div(id="online-analysis-mapping-section"),
                
                # Store for detected keys
                dcc.Store(id="online-analysis-detected-keys", storage_type="session"),
                # Store for the confirmed mapping {file_key: objective_name}
                dcc.Store(id="online-analysis-key-mapping", storage_type="session"),
            ]),
            
            # ===== MONITORING SECTION (visible when ON) =====
            html.Div(id="online-analysis-monitor", style={"display": "none"}, children=[
                # Status badges
                dbc.Row([
                    dbc.Col([
                        html.Div([
                            dbc.Badge(
                                id="online-analysis-phase-badge",
                                children="Initialization",
                                color="info",
                                className="me-2",
                                style={"fontSize": "0.8rem"}
                            ),
                            dbc.Badge(
                                id="online-analysis-status-badge",
                                children="Waiting for results...",
                                color="warning",
                                style={"fontSize": "0.8rem"}
                            ),
                        ])
                    ], md=12, className="mb-3")
                ]),
                
                # Active mapping display
                html.Div(id="online-analysis-active-mapping", className="mb-3"),
                
                # Progress
                dbc.Row([
                    dbc.Col([
                        html.Div([
                            html.Span("Progress: ", className="fw-bold",
                                     style={"fontSize": "0.85rem"}),
                            html.Span(
                                id="online-analysis-progress-text",
                                children="0 / ? results received",
                                style={"fontSize": "0.85rem"}
                            )
                        ]),
                        dbc.Progress(
                            id="online-analysis-progress-bar",
                            value=0,
                            className="mt-2",
                            style={"height": "8px"}
                        )
                    ], md=12, className="mb-3")
                ]),
                
                # Activity log
                dbc.Row([
                    dbc.Col([
                        dbc.Label("Activity Log", className="fw-bold mb-1",
                                 style={"fontSize": "0.85rem"}),
                        html.Div(
                            id="online-analysis-log",
                            style={
                                "maxHeight": "150px",
                                "overflowY": "auto",
                                "backgroundColor": "#1a1a2e",
                                "color": "#00ff88",
                                "fontFamily": "monospace",
                                "fontSize": "0.75rem",
                                "padding": "0.75rem",
                                "borderRadius": "6px",
                                "whiteSpace": "pre-wrap"
                            },
                            children="Monitoring started..."
                        )
                    ], md=12, className="mb-3")
                ]),
                
                # Stop button
                dbc.Row([
                    dbc.Col([
                        dbc.Button([
                            html.I(className="bi bi-stop-circle me-2"),
                            "Stop Monitoring"
                        ],
                        id="online-analysis-stop-btn",
                        color="danger",
                        outline=True,
                        size="sm",
                        style={"fontWeight": "500"}
                        )
                    ])
                ])
            ]),
            
            # ===== HIDDEN COMPONENTS =====
            dcc.Interval(
                id="online-analysis-interval-component",
                interval=5 * 1000,
                disabled=True,
                n_intervals=0
            ),
            
            dcc.Store(
                id="online-analysis-state",
                storage_type="session",
                data={
                    "enabled": False,
                    "filepath": "",
                    "phase": "initialization",
                    "results_processed": 0,
                    "total_init_experiments": 0,
                    "log_entries": [],
                    "last_file_mtime": None,
                    "bo_iteration": 0,
                }
            ),
            
        ], style={"padding": "1rem"})
    ], style={
        "borderRadius": "12px",
        "border": "1px solid #e0e0e0",
        "boxShadow": "0 2px 8px rgba(0,0,0,0.06)",
        "backgroundColor": "white"
    })